<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-JOPOHLMU" ignored="0" name="RegressionTests" tests="2" failures="1" timestamp="21 Sep 2020 19:55:58 GMT" time="62.27" errors="0">
  <testcase name="verifyPageTitle" time="5.622" classname="com.qa.automation.ndtv.weatherreporting.tests.SimpleTests"/>
  <testcase name="captureWeatherDetailsFromUIAndApi" time="36.869" classname="com.qa.automation.ndtv.weatherreporting.tests.WeatherReportingTests">
    <failure type="java.lang.AssertionError" message="Exception: Cause- AssertionError, null, Message- The following asserts failed:
	Failed to get valid response from API">
      <![CDATA[java.lang.AssertionError: Exception: Cause- AssertionError, null, Message- The following asserts failed:
	Failed to get valid response from API
	at com.qa.automation.ndtv.weatherreporting.tests.WeatherReportingTests.captureWeatherDetailsFromUIAndApi(WeatherReportingTests.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- captureWeatherDetailsFromUIAndApi -->
</testsuite> <!-- RegressionTests -->
